<?php
$from = sanitize_text_field((string)($_GET['date_from'] ?? gmdate('Y-m-d', strtotime('-7 days'))));
$to = sanitize_text_field((string)($_GET['date_to'] ?? current_time('Y-m-d')));
$data = COD_CRM_DB::get_reports_data($from, $to);
?>
<div class="wrap cod-crm-wrap"><h1>Reports & Analytics</h1>
<form method="get" class="cod-crm-filters"><input type="hidden" name="page" value="cod-crm-reports"><input type="date" name="date_from" value="<?php echo esc_attr($from); ?>"><input type="date" name="date_to" value="<?php echo esc_attr($to); ?>"><button class="button">Apply</button></form>
<div class="cod-crm-card"><h2>Daily Summary</h2><table class="widefat striped"><thead><tr><th>Date</th><th>Total</th><th>Confirmed</th><th>Cancelled</th><th>No Answer</th><th>Wrong No.</th><th>Not Picked</th><th>Switched Off</th><th>Busy</th><th>Callback</th><th>Prepaid</th><th>Rate %</th></tr></thead><tbody><?php foreach($data['daily'] as $r): $rate=$r['total']>0?round(($r['confirmed']/$r['total'])*100,2):0; ?><tr><td><?php echo esc_html($r['d']); ?></td><td><?php echo esc_html($r['total']); ?></td><td><?php echo esc_html($r['confirmed']); ?></td><td><?php echo esc_html($r['cancelled']); ?></td><td><?php echo esc_html($r['no_answer']); ?></td><td><?php echo esc_html($r['wrong_number']); ?></td><td><?php echo esc_html($r['not_picked']); ?></td><td><?php echo esc_html($r['switched_off']); ?></td><td><?php echo esc_html($r['busy']); ?></td><td><?php echo esc_html($r['callback_requested']); ?></td><td><?php echo esc_html($r['prepaid']); ?></td><td><?php echo esc_html((string)$rate); ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="cod-crm-card"><h2>Agent Performance</h2><table class="widefat striped"><thead><tr><th>Agent</th><th>Total Calls</th><th>Confirmed</th><th>Cancelled</th><th>Avg Duration</th><th>Confirm Rate %</th><th>Pending Callbacks</th></tr></thead><tbody><?php foreach($data['agent'] as $r): $u=get_user_by('id',intval($r['agent_id'])); $rate=$r['total_calls']>0?round(($r['confirmed']/$r['total_calls'])*100,2):0; ?><tr><td><?php echo esc_html($u?$u->display_name:'System'); ?></td><td><?php echo esc_html($r['total_calls']); ?></td><td><?php echo esc_html($r['confirmed']); ?></td><td><?php echo esc_html($r['cancelled']); ?></td><td><?php echo esc_html(round((float)$r['avg_duration'],2)); ?></td><td><?php echo esc_html((string)$rate); ?></td><td><?php echo esc_html($r['pending_callbacks']); ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="cod-crm-card"><h2>Outcome Distribution</h2><canvas id="codCrmPieChart" height="120"></canvas></div>
<div class="cod-crm-card"><h2>Attempt Analysis</h2><p>1st attempt confirms: <strong><?php echo esc_html((string)$data['attempt']['a1']); ?></strong> | 2nd attempt confirms: <strong><?php echo esc_html((string)$data['attempt']['a2']); ?></strong> | 3rd attempt confirms: <strong><?php echo esc_html((string)$data['attempt']['a3']); ?></strong></p></div>
<div class="cod-crm-card"><h2>RTO Risk Report</h2><table class="widefat striped"><thead><tr><th>Order ID</th><th>Customer</th><th>Phone</th><th>Attempts</th><th>Last Outcome</th><th>Last Called</th></tr></thead><tbody><?php foreach($data['rto'] as $r): ?><tr><td><?php echo esc_html($r['order_id']); ?></td><td><?php echo esc_html($r['customer_name']); ?></td><td><?php echo esc_html($r['customer_phone']); ?></td><td><?php echo esc_html($r['total_attempts']); ?></td><td><?php echo esc_html($r['last_outcome']); ?></td><td><?php echo esc_html($r['last_called']); ?></td></tr><?php endforeach; ?></tbody></table></div>
</div>
<script>window.codCrmOutcomeDistribution = <?php echo wp_json_encode($data['distribution']); ?>;</script>
